# REACT
name: Build and Deploy to Cloud Storage

on:
  push:
    branches: ["main"]
    paths:
      - "react/**"

env:
  PROJECT_ID: jbaaam # TODO: update Google Cloud project id
  GAR_NAME: ghaction # TODO: update Artifact Registry location
  GAR_LOCATION: asia-southeast1 # TODO: update Artifact Registry location
  SERVICE: jbaaam # TODO: update Cloud Run service name
  REGION: asia-southeast2 # TODO: update Cloud Run service region

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest #OS of machine(in github) that executes workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Specify the Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: ./react

      - name: Build React app
        run: |
          # ensure warnings are not errors and fail
          export CI=false
          npm run build
        working-directory: ./react

      # - name: test
      #   run:

      # NOTE: Alternative option - authentication via credentials json, SERVICE ACC
      - name: Google Auth
        id: auth
        # Check latest version: https://github.com/google-github-actions/auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Deploy to Cloud Storage
        id: "upload-file"
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "./react/build/**"
          destination: "jbaaam_frontend"
